# Generated by Django 3.2.16 on 2023-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('questions', models.TextField(max_length=500, verbose_name='questions')),
                ('first_variant', models.CharField(max_length=300, verbose_name='first_variant')),
                ('second_variant', models.CharField(max_length=300, verbose_name='second_variant')),
                ('third_variant', models.CharField(max_length=300, verbose_name='third_variant')),
                ('fourth_variant', models.CharField(max_length=300, verbose_name='fourth_variant')),
            ],
        ),
    ]
