# Generated by Django 3.2.16 on 2023-01-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20230105_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodelcategories',
            name='quantity',
        ),
    ]
