# Generated by Django 3.2.16 on 2023-01-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_testmodelcategories_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='name',
            new_name='category',
        ),
    ]
