# Generated by Django 3.2.16 on 2023-01-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_rename_name_testmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='answer',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='answer'),
        ),
    ]
