# Generated by Django 3.2.16 on 2023-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_testmodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=1, max_length=10, verbose_name='answer'),
            preserve_default=False,
        ),
    ]
